[containers]
http_proxy = false

[engine]
env = [
  "http_proxy=http://127.0.0.1:7890",
  "https_proxy=http://127.0.0.1:7890",
  "no_proxy=localhost,127.0.0.1,docker.1ms.run,docker.m.daocloud.io,docker.nju.edu.cn"
]

[machine]

[network]

[secrets]

[configmaps]
